name: itslive-notebooks
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - fiona
  - ipyleaflet
  - ipympl
  - jupyterlab=3
  - matplotlib-base
  - pandas
  - pyproj
  - s3fs>=2021.11
  - sidecar
  - shapely
  - xarray
  - zarr
