name: itslive-notebooks
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - fiona
  - ipympl
  - matplotlib-base
  - pandas
  - pyproj
  - s3fs
  - sidecar
  - shapely
  - xarray
  - markdown
  - voila
  - zarr
  - pip
  - pip:
    - git+https://github.com/jupyter-widgets/ipyleaflet.git
