name: itslive-notebooks
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab=3.3
  - traitlets=5.0.5
  - fiona
  - ipyleaflet
  - ipympl
  - matplotlib-base
  - pandas
  - pyproj
  - s3fs
  - sidecar
  - shapely
  - xarray
  - voila
  - zarr
